analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.92519
title: Mehmet Ali Yücel
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.0625
  brandStrength: 0.6875
  rhythmicContrast: 1
  brandColors:
    - '#fdfdfd'
    - '#696969'
    - '#060606'
    - '#9c9c9c'
    - '#3f3f3f'
  lightness: 0.5
purpose: []
favicon: null
name: Mehmet Ali Yücel
typography_spectrum: 0.85504
