title: Mehmet Ali Yücel
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7060932
  brandStrength: 1
  lightness: 0.6326165
  brandColors:
    - '#fdfdfd'
    - '#696969'
    - '#060606'
    - '#9c9c9c'
    - '#3f3f3f'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Mehmet Ali Yücel
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.85504
layout_spectrum: 1
