name: Mehmet Ali Yücel
favicon: null
layout_spectrum: 0.92519
typography_spectrum: 0.85504
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Mehmet Ali Yücel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#696969'
    - '#060606'
    - '#9c9c9c'
    - '#3f3f3f'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
